# Changes here will be overwritten by Copier
_commit: 68ae1a9
_src_path: https://github.com/bhklab/bhklab-project-template
author_email: bhklab.jermiahjoseph@gmail.com
author_full_name: Jermiah Joseph
github_username: jjjermiah
project_description: Agony implementation
project_name: Agony
project_slug: agony
python_version: '3.10'
repo_location: bhklab
