# package building
[package]
name = "agony"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.1.*" }

[package.host-dependencies]
cmake = ">=4.0.0"
nanobind = "2.7.*"
python = "3.10.*"
